### ISSUE TITLE
Fumetto del tutorial

### ISSUE THREAD

**Issue by Andrea-Maffia** [knickita/matematica#16]
Quando si arriva a imparare il comando INCOLLA il fumetto dice "dobbiamo solo PIù imparare", quel 'più' è da eliminare. Dietro a quel fumetto sembra anche essere nascosta una freccia che però non serve in quel momento

**Comment by knickita** [comment]
si e io cambierei anche INCOLLA con COLLA (visto che più avanti nel tutorial lo chiamiamo così)

**Comment by Andrea-Maffia** [comment]
> si e io cambierei anche INCOLLA con COLLA (visto che più avanti nel tutorial lo chiamiamo così)

Concordo!
