### ISSUE TITLE
Tutorial: inserimento numeri sui rettangoli

### ISSUE THREAD

**Issue by Andrea-Maffia** [knickita/matematica#17]
Subito dopo aver tagliato il rettangolo in due, si chiede di inserire i numeri dei nuovi rettangoli. Se viene fatto nella schermata aritmetica, nessun problema. Se però si tenta di farlo cliccando sui rettangoli, questo non funziona perché si ha selezionato il comando taglia. Forse in qualche momento (prima? quando si diceva che si possono inserire i numeri sui rettangoli) bisogna specificare che per inserire i numeri sui rettangoli bisogna aver selezionato il comando MATITA (è così, giusto?)

**Comment by knickita** [comment]
ho corretto il tutorial in modo che la prima volta che ti fa inserire un numero ti spiega che devi avere la matita selezionata. per sicurezza te lo ricorda ancora in alcune istruzioni successive.
