### ISSUE TITLE
Leggibilità scritte tutorial

### ISSUE THREAD

**Issue by Andrea-Maffia** [knickita/matematica#19]
Le scritte durante il tutorial appaiono molto sfocate (quantomeno su Chrome)

**Comment by knickita** [comment]
sul mio computer questo effetto non lo vedo tantissimo, però paragonato ad altre scritte su altri siti web effettivamente è un pò più sfocato.

risolto raddoppiando la risoluzione a cui viene disegnato il testo...

bisognerà fare alcuni test ed avere dei riscontri dagli utenti
