### ISSUE TITLE
Posizione fumetto nel tutorial

### ISSUE THREAD

**Issue by Andrea-Maffia** [knickita/matematica#21]
Nella parte del tutorial relativa al comando di rotazione, i fumetti che chiedono prima di ruotare 2x6 e poi 5x6 sono esattamente nella stessa posizione e quindi l'utente potrebbe non rendersi conto del cambiamento del testo del fumetto. Forse si potrebbe fare in modo che il fumetto la seconda volta appaia in una posizione un po' diversa?

**Comment by knickita** [comment]
spostarlo era un pò complicato perchè non si sa dove l'utente abbia disegnato i rettangoli in quel momento, e si rischia di coprirli.. ho aggiunto un riga iniziale con scritto "Ottimo!". in questo modo il rettangolo appare più grande del precedente e l'utente si accorge che c'è una nuova istruzione
